- name: THÊM THÔNG TIN /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    state: present
    block: |
      {{IP_LOADBALANCING}} {{DOMAIN_CLUSTER}}

- name: HOSTNAME MASTER
  set_fact:
    hostname: "{{EVN_SV}}-{{HOSTNAME_SV}}-master{{ item }}"
  loop: "{{ range(1, groups['masters']|length + 1)|list }}"
  when: inventory_hostname == groups['masters'][item - 1]

- name: HOSTNAME SLAVES
  set_fact:
    hostname: "{{EVN_SV}}-{{HOSTNAME_SV}}-slaves{{ item }}"
  loop: "{{ range(1, groups['slaves']|length + 1)|list }}"
  when: inventory_hostname == groups['slaves'][item - 1]

- name: ĐẶT TÊN CHO HOSTNAME
  ansible.builtin.hostname:
    name: "{{ hostname }}"