- name: ==================================== KIEM TRA BIEN MOI TRUONG TRONG ANSIBLE  ====================================
  hosts: k8s-cluster
  gather_facts: false
  tasks:
    - name: ENV ANSIBLE
      include_vars:
        file: global_vars/var-manager.yaml
        #file: global_vars/var-application.yaml

- name: ==================================== BRAVO - RANCHER RKE2 AUTOMATION ====================================
  hosts: k8s-cluster
  roles:
    #  - pingCheck
    #  - createFileHost
    # ##################### CÀI ĐẶT MASTER VÀ JOIN MASTER ####################   
    #  - role: createFirstMaster
    #    when: inventory_hostname in groups['masters']
    #  - role: joinMasterOther
    #    when: inventory_hostname in groups['masters']
    # ####################### JOIN WORKER ####################
    #  - joinWorkerOther
    #  - setupPluginKube
     - deleteCommon
