# Thông tin chung version K8S
VERSION_k8s: 1.28
VERSION_PATCH: 14-2.1


######### Version RKE2
VERSION_RKE2: v1.30.6+rke2r1

######### Tên host name
HOSTNAME_SV: rke2-app01
EVN_SV: uat

######### Thông tin load balancing RKE2
IP_LOADBALANCING: 192.168.130.210
DOMAIN_CLUSTER: uat-rke2-app01.bravo.com.vn
PORT_RKE2_SERVICE: 9345
