# ############## CHECK THÔNG TIN MASTER  ####################
- name: MASTER FIRST
  ansible.builtin.set_fact:
    is_first_master: "{{ ansible_play_hosts.index(inventory_hostname) == 0 }}"

- name: MASTER OTHER
  ansible.builtin.set_fact:
    is_other_master: "{{ ansible_play_hosts.index(inventory_hostname) > 0 }}"

# Create token join node
- name: CHECK TOKEN JOIN
  shell: cat /var/lib/rancher/rke2/server/node-token
  register: kubeadm_join_command
  when: is_first_master

- name: TOKEN
  set_fact:
    command_join_cluster: "{{ kubeadm_join_command.stdout }}"
  when: is_first_master
  run_once: true

# - name: VERIFY TOKEN
#   debug:
#     var: command_join_cluster
#   when: is_first_master

# Tạo Certificate Join cluster node master
- name: KHOI TAO CONFIG CHO OTHER CLUSTER
  shell: |
    mkdir -p /etc/rancher/rke2
    touch /etc/rancher/rke2/config.yaml
    mkdir -p /var/backups/etcd-snapshot
    echo "write-kubeconfig-mode: 0600
    server: https://{{IP_FIRST_MASTER}}:{{PORT_RKE2_SERVICE}}
    token: {{ command_join_cluster }}
    tls-san:
      - {{IP_FIRST_MASTER}}
    disable-kube-proxy: no
    disable:
      - rke2-ingress-nginx
    disable-cloud-controller: yes
    #### ETCD ####
    etcd-snapshot-name: etcd-uat
    etcd-snapshot-schedule-cron: \"0 12 * * *\"
    etcd-snapshot-retention: 5
    etcd-snapshot-dir: /var/backups/etcd-snapshot
    etcd-snapshot-compress: true

    #-------------- API-SERVER --------------
    ## flag 
    kube-apiserver-arg:                               
      - authorization-mode=RBAC,Node
      - anonymous-auth=false

    #-------------- CONTROL-PLANE --------------
    ## Resource
    control-plane-resource-requests:                  
      - kube-apiserver-cpu=800m
      - kube-apiserver-memory=1512M
      - kube-scheduler-cpu=550m
      - kube-scheduler-memory=512M
      - etcd-cpu=1500m
    #control-plane-resource-limits:                  
    ## Resource  

    #-------------- KUBE-PROXY --------------
    #kube-proxy-arg:                                   

    #-------------- KUBE-SCHEDULES --------------
    #kube-scheduler-arg:
    kube-scheduler-extra-env: "TZ=Asia/Ho_Chi_Minh"    

    #-------------- KUBELET --------------
    kubelet-arg:
    - kube-reserved=cpu=500m,memory=2Gi
    - system-reserved=cpu=500m,memory=2Gi" > /etc/rancher/rke2/config.yaml



  register: create_join_cluster
  when: is_other_master

# - name: KET QUA
#   debug:
#     var: create_join_cluster
#   when: is_other_master

- name: ENABLE SERVICE RKE2-SERVER TREN NODE OTHER
  shell: systemctl start rke2-server.service
  when: is_other_master
  register: rke2_debug

- name: DEBUG
  debug:
    var: rke2_debug
