# Check node Master chính
- name: KIEM TRA MASTER DAU TIEN
  ansible.builtin.set_fact:
    is_first_master: "{{ ansible_play_hosts.index(inventory_hostname) == 0 }}"

- name: KIEM TRA MASTER KHAC
  ansible.builtin.set_fact:
    is_other_master: "{{ ansible_play_hosts.index(inventory_hostname) > 0 }}"


# Init First Node Master
- name: CAI DAT RKE2-SERVER
  shell: |
    curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION={{VERSION_RKE2}} INSTALL_RKE2_TYPE=server sh -
  when: is_first_master
  register: rke2_setup

- name: CHECK LIST CAI DAT 
  debug:
    var: rke2_setup
  when: is_first_master

# #  tạo thư mục service account
# - name: Tạo thư mục service account
#   shell: |
#     mkdir -p $HOME/.kube
#     cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
#     chown $(id -u):$(id -g) $HOME/.kube/config
#   when: is_first_master
#   register: createfolder

# - name: Tạo thư mục service account
#   debug:
#     var: createfolder
#   when: is_first_master

    