# Check node Master chính
- name: XÁC ĐỊNH HOST MASTER FIRST
  ansible.builtin.set_fact:
    is_first_master: "{{ groups['masters'].index(inventory_hostname) == 0 }}"

- name: XÁC ĐỊNH HOST MASTER OTHER
  ansible.builtin.set_fact:
    is_other_master: "{{ groups['masters'].index(inventory_hostname) > 0 }}"

# - name: IN KẾT QUẢ HOST MASTER ĐẦU TIÊN
#   debug:
#     msg: "Host này là master đầu tiên"
#   when: is_first_master

# - name: IN KẾT QUẢ HOST MASTER KHÁC
#   debug:
#     msg: "Host này là master khác"
#   when: is_other_master

# CÀI ĐẶT RKE2-SERVER
- name: CAI DAT RKE2-SERVER
  shell: |
    wget -qO - https://get.rke2.io | INSTALL_RKE2_VERSION={{VERSION_RKE2}}  INSTALL_RKE2_TYPE=server sh -
  when: is_first_master or is_other_master
  register: rke2_setup

- name: CHECK LIST CAI DAT
  debug:
    var: rke2_setup

- name: Copy Kubernetes manifest to remote server
  copy:
    src: "../../../script"
    dest: "/tmp"
    mode: '0755'
    directory_mode: '0755'
  when: is_first_master

#  tạo thư mục service account
- name: TAO CAU HINH RKE2
  shell: |
    mkdir -p /etc/rancher/rke2
    touch /etc/rancher/rke2/config.yaml
    mkdir -p /var/backups/etcd-snapshot
    echo "write-kubeconfig-mode: 0600
    tls-san:
      - {{DOMAIN_MANAGER}}
      - {{IP_LOADBALANCING}}
    disable-kube-proxy: no
    disable:
      - rke2-ingress-nginx
    disable-cloud-controller: yes
    #### ETCD ####
    etcd-snapshot-name: etcd-master-snapshot
    etcd-snapshot-schedule-cron: \"0 12 * * *\"
    etcd-snapshot-retention: 5
    etcd-snapshot-dir: /var/backups/etcd-snapshot
    etcd-snapshot-compress: true

    #-------------- KUBELET --------------
    ## flag
    kubelet-arg:                                     
      - kube-reserved=cpu=400m,memory=2Gi
      - system-reserved=cpu=400m,memory=2Gi
      - max-pods=200

    #-------------- API-SERVER --------------
    ## flag 
    kube-apiserver-arg:                               
      - authorization-mode=RBAC,Node
      - anonymous-auth=false

    #-------------- CONTROL-PLANE --------------
    ## Resource
    control-plane-resource-requests:                  
      - kube-apiserver-cpu=1000m
      - kube-apiserver-memory=1500M
      - kube-scheduler-cpu=1500m
      - kube-scheduler-memory=1000M
      - etcd-cpu=1500m
    #control-plane-resource-limits:                  
    ## Resource  

    #-------------- KUBE-PROXY --------------
    #kube-proxy-arg:                                   

    #-------------- KUBE-SCHEDULES --------------
    #kube-scheduler-arg:
    kube-scheduler-extra-env: "TZ=Asia/Ho_Chi_Minh"    

    
    > /etc/rancher/rke2/config.yaml

  when: is_first_master

- name: ENABLE SERVICE RKE2-SERVER
  shell: systemctl start rke2-server.service
  when: is_first_master
  register: rke2_debug

- name: DEBUG SERVICE RKE2-SERVER
  debug:
    var: rke2_debug